version: '2'
services: 
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_HOST: localhost
      # MYSQL_DATABASE: noteapp   #ko can phai rails db:create
      # MYSQL_USER: appuser
      # MYSQL_PASSWORD: 12345678
    ports: 
      - "3308:3306"
    expose: 
      - 3306
    container_name: DB_Service
  app:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes: 
      - ".:/noteapp"
    ports: 
      - "3003:3000"
      - "3330:3333"
    depends_on: # db phai chay truoc thang app
      - db
    # links: #link voi services db co the connect thong qua ten la db
    #   - db
    environment: 
      DB_USERNAME: root
      DB_PASSWORD: 12345678
      # DB_NAME: noteapp
      DB_HOST: db 
      DB_SOCKET: /var/run/mysqld/mysqld.sock
      DB_PORT: 3306
      # DB_URL: 'mysql2://db'
      RAILS_ENV: 'development'
      DATABASE_URL: 'mysql2://db'
    # restart: always
